from django import forms

class UserForm(forms.Form):
    Latitude= forms.FloatField()
    Longitude= forms.FloatField()
    apparentTemperatureMax= forms.FloatField()
    apparentTemperatureMin= forms.FloatField()
    cloudCover= forms.FloatField()
    dewPoint= forms.FloatField()
    humidity= forms.FloatField()
    precipIntensity= forms.FloatField()
    precipIntensityMax= forms.FloatField()
    precipProbability= forms.FloatField()
    precipAccumulation= forms.FloatField()
    precipTypeIsRain= forms.FloatField()
    precipTypeIsSnow= forms.FloatField()
    precipTypeIsOther= forms.FloatField()
    pressure= forms.FloatField()
    temperatureMax= forms.FloatField()
    temperatureMin= forms.FloatField()
    visibility= forms.FloatField()
    windBearing= forms.FloatField()
    windSpeed= forms.FloatField()
    NDVI= forms.FloatField()
    DayInSeason= forms.FloatField()